cluster.name: os-cluster
network.host: 0.0.0.0

bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping

cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 93%
cluster.routing.allocation.disk.watermark.high: 95%

plugins.security.allow_unsafe_democertificates: true
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemtrustedcas_filepath: certificates/ca/ca.pem
plugins.security.ssl.transport.enabled: true
plugins.security.ssl.transport.pemtrustedcas_filepath: certificates/ca/ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]

plugins.security.authcz.admin_dn:
  - 'CN=ADMIN,O=Team-ACD,L=Rome,ST=Italy,C=IT'
plugins.security.nodes_dn:
  - 'CN=os00,O=Team-ACD,L=Rome,ST=Italy,C=IT'
  - 'CN=os01,O=Team-ACD,L=Rome,ST=Italy,C=IT'
  - 'CN=os02,O=Team-ACD,L=Rome,ST=Italy,C=IT'
  - 'CN=os03,O=Team-ACD,L=Rome,ST=Italy,C=IT'
  - 'CN=os04,O=Team-ACD,L=Rome,ST=Italy,C=IT'
  - 'CN=os05,O=Team-ACD,L=Rome,ST=Italy,C=IT'
  - 'CN=os06,O=Team-ACD,L=Rome,ST=Italy,C=IT'
  - 'CN=os07,O=Team-ACD,L=Rome,ST=Italy,C=IT'
